# -*- coding: utf-8 -*-
"""BI PRAC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tnyyrjF3rqXP_mRi371XsoNI8tQ8hUiA
"""

w

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""i have imported the libraries"""

kent = pd.read_csv('/content/apple.csv')

"""to import the dataset"""

kent.head()

"""reading the dataset"""

kent.head(20)

"""reading only  the first 20

```
# This is formatted as code
```


"""

kent.tail()

"""reading the last 5"""

kent.shape

"""how many columns and rows our dataset has"""

kent.dtypes

"""what are the data types in column"""

kent.describe()

"""summary statisitcial analysis of our data"""

kent.info()

"""no null there is no missing value...it helps us to confirm that we dont have missing value."""

kent.isnull().sum()

"""it counts the null values."""

kent.isnull()

"""proving if we have a missing value"""

joan = pd.read_excel('SalesTransactions.xlsx')

joan.shape

joan = pd.read_excel('/content/SalesTransactions.xlsx')

joan.head

joan.isnull()

joan.isnull().sum()

joan.isna()

"""tell us which ones are missing"""

kent.duplicated()

"""shows how many are deuplicated"""